--!strict

local WorldTags = {
	Customer = "Customer",
	StaffNpc = "StaffNpc",
	SecurityCamera = "SecurityCamera",
	CustomerSpawn = "CustomerSpawn",
	CustomerExit = "CustomerExit",
	BrowsePoint = "BrowsePoint",
	CheckoutPoint = "CheckoutPoint",
	ShelfPoint = "ShelfPoint",
	StoreInteractable = "StoreInteractable",

	StoreNavNode = "StoreNavNode",
	EntranceNode = "EntranceNode",
	ExitNode = "ExitNode",
	CheckoutNode = "CheckoutNode",
	ShelfNavNode = "ShelfNavNode",
	StoreWalkZone = "StoreWalkZone",
}

return WorldTags